apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AdhamAyad/argocd-app.git
    targetRevision: main
    path: kube-watch
    #directory:
    #recurse: true
    #include: '*.yaml'
    #exclude: '*_test.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
